<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'PortableTests'">
    <BaseOutputPath>$(MSBuildThisFileDirectory)..\Tools\PortableOutput\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)..\Tools\PortableOutput\obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
