#if TAF_TESTS
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading;
using NUnit.Framework;
using ThousandAndFirst.Simulation.Kernel;

namespace ThousandAndFirst.Tests
{
	/// <summary>
	/// Goldens here are hard-coded, never generated by the code under test. A golden derived from
	/// the implementation proves only that the implementation agrees with itself.
	/// </summary>
	public class KernelCanonicalTests
	{
		internal const string GoldenSettlement = "taf:settlement:test";

		internal const string GoldenStream = "taf:stream:test";

		internal const int GoldenRules = 3;

		internal const uint GoldenKind = 1u;

		internal const ulong GoldenOrdinal = 42uL;

		internal const string GoldenEventPreimage =
			"5441465f45565431000102030405060708090a0b0c0d0e0f00000003000000137461663a736574746c65"
			+ "6d656e743a746573740000000f7461663a73747265616d3a7465737400000001000000000000002a";

		internal const string GoldenEventDigestId =
			"taf:event:v1:dfb981b1614454174bb61b01f3495cd4e74b31e73ada138b563c0a62d8eb7c56";

		internal const string GoldenRandomPreimage =
			"5441465f524e4731000102030405060708090a0b0c0d0e0f00000003000000137461663a736574746c65"
			+ "6d656e743a746573740000000f7461663a73747265616d3a7465737400000001000000000000002a00"
			+ "00000700000000";

		internal static KernelSeed128 GoldenSeed()
		{
			return new KernelSeed128(0x0001020304050607uL, 0x08090A0B0C0D0E0FuL);
		}

		internal static SemanticEventKey GoldenKey()
		{
			SemanticEventKey key;
			KernelFaultCode fault;
			Assert.IsTrue(SemanticEventKey.TryCreate(GoldenRules, GoldenSettlement, GoldenStream, GoldenKind, GoldenOrdinal, out key, out fault));
			return key;
		}

		internal static string Hex(byte[] bytes)
		{
			return KernelDigest.ToLowercaseHex(bytes);
		}

		internal static string Clean(string spaced)
		{
			return spaced.Replace(" ", string.Empty);
		}

		[Test]
		public void EventPreimageMatchesTheHardCodedGolden()
		{
			byte[] bytes;
			KernelFaultCode fault;
			Assert.IsTrue(KernelCanonicalEncoding.TryEncodeEventIdentityPreimage(GoldenSeed(), GoldenKey(), out bytes, out fault));
			Assert.AreEqual(KernelFaultCode.None, fault);
			Assert.AreEqual(GoldenEventPreimage, Hex(bytes));
			Assert.AreEqual(82, bytes.Length, "48 fixed bytes plus both length-prefixed identifiers");
		}

		[Test]
		public void RandomPreimageMatchesTheHardCodedGolden()
		{
			byte[] bytes;
			KernelFaultCode fault;
			Assert.IsTrue(KernelCanonicalEncoding.TryEncodeRandomBlockPreimage(GoldenSeed(), GoldenKey(), 7u, 0u, out bytes, out fault));
			Assert.AreEqual(GoldenRandomPreimage, Hex(bytes));
			Assert.AreEqual(90, bytes.Length);
		}

		[Test]
		public void EventIdMatchesTheHardCodedGolden()
		{
			string id;
			KernelFaultCode fault;
			Assert.IsTrue(SemanticEventIdentity.TryCreateId(GoldenSeed(), GoldenKey(), out id, out fault));
			Assert.AreEqual(GoldenEventDigestId, id);
		}

		[Test]
		public void TheTwoDomainsDifferOnlyByTheirTagAndAreNeverEqual()
		{
			byte[] eventBytes;
			byte[] randomBytes;
			KernelFaultCode fault;
			KernelCanonicalEncoding.TryEncodeEventIdentityPreimage(GoldenSeed(), GoldenKey(), out eventBytes, out fault);
			KernelCanonicalEncoding.TryEncodeRandomBlockPreimage(GoldenSeed(), GoldenKey(), 0u, 0u, out randomBytes, out fault);

			Assert.AreEqual("5441465f45565431", Hex(eventBytes).Substring(0, 16));
			Assert.AreEqual("5441465f524e4731", Hex(randomBytes).Substring(0, 16));
			for (int i = 8; i < eventBytes.Length; i++)
			{
				Assert.AreEqual(eventBytes[i], randomBytes[i], "shared body must be byte-identical after the tag, at offset " + i);
			}
		}

		[TestCase(0)]
		[TestCase(1)]
		[TestCase(int.MaxValue)]
		[TestCase(int.MinValue)]
		[TestCase(-1)]
		public void Int32IsBigEndianTwosComplement(int value)
		{
			using (CanonicalByteWriter writer = new CanonicalByteWriter())
			{
				writer.WriteInt32(value);
				byte[] bytes = writer.ToArray();
				Assert.AreEqual(4, bytes.Length);
				uint unsigned = unchecked((uint)value);
				Assert.AreEqual((byte)(unsigned >> 24), bytes[0]);
				Assert.AreEqual((byte)(unsigned >> 16), bytes[1]);
				Assert.AreEqual((byte)(unsigned >> 8), bytes[2]);
				Assert.AreEqual((byte)unsigned, bytes[3]);
			}
		}

		[TestCase(0L)]
		[TestCase(1L)]
		[TestCase(long.MaxValue)]
		[TestCase(long.MinValue)]
		[TestCase(-1L)]
		public void Int64IsBigEndianTwosComplement(long value)
		{
			using (CanonicalByteWriter writer = new CanonicalByteWriter())
			{
				writer.WriteInt64(value);
				byte[] bytes = writer.ToArray();
				Assert.AreEqual(8, bytes.Length);
				ulong unsigned = unchecked((ulong)value);
				for (int i = 0; i < 8; i++)
				{
					Assert.AreEqual((byte)(unsigned >> (56 - (8 * i))), bytes[i], "byte " + i);
				}
			}
		}

		[Test]
		public void BoolIsExactlyZeroOrOne()
		{
			using (CanonicalByteWriter writer = new CanonicalByteWriter())
			{
				writer.WriteBool(false);
				writer.WriteBool(true);
				Assert.AreEqual("0001", Hex(writer.ToArray()));
			}
		}

		[Test]
		public void RequiredUtf8IsLengthPrefixedStrictAndBomFree()
		{
			using (CanonicalByteWriter writer = new CanonicalByteWriter())
			{
				writer.WriteRequiredUtf8("ab");
				Assert.AreEqual("000000026162", Hex(writer.ToArray()));
			}
			using (CanonicalByteWriter writer = new CanonicalByteWriter())
			{
				// Empty is legal at the writer layer; the Try* encoders validate identifiers above it.
				writer.WriteRequiredUtf8(string.Empty);
				Assert.AreEqual("00000000", Hex(writer.ToArray()));
			}
			using (CanonicalByteWriter writer = new CanonicalByteWriter())
			{
				// Non-identity payload text may be non-ASCII, so the writer must handle it.
				writer.WriteRequiredUtf8("\u00e9");
				Assert.AreEqual("00000002c3a9", Hex(writer.ToArray()), "no BOM, two UTF-8 bytes");
			}
		}

		[Test]
		public void ComposedAndDecomposedTextAreDifferentBytesBecauseNothingNormalizes()
		{
			string composedText = "\u00e9";
			string decomposedText = "e\u0301";
			using (CanonicalByteWriter composed = new CanonicalByteWriter())
			using (CanonicalByteWriter decomposed = new CanonicalByteWriter())
			{
				composed.WriteRequiredUtf8(composedText);
				decomposed.WriteRequiredUtf8(decomposedText);
				Assert.AreEqual("00000002c3a9", Hex(composed.ToArray()));
				Assert.AreEqual("0000000365cc81", Hex(decomposed.ToArray()));
				Assert.AreNotEqual(Hex(composed.ToArray()), Hex(decomposed.ToArray()),
					"normalizing would silently merge two distinct inputs into one identity");
			}
		}

		[Test]
		public void MalformedUtf16AndNullAreRefused()
		{
			using (CanonicalByteWriter writer = new CanonicalByteWriter())
			{
				Assert.Throws<ArgumentNullException>(delegate { writer.WriteRequiredUtf8(null); });
				Assert.Throws<ArgumentNullException>(delegate { writer.WriteRawBytes(null); });
				// A lone high surrogate must throw rather than be replaced by U+FFFD, which would
				// make two different inputs encode identically.
				Assert.Throws<System.Text.EncoderFallbackException>(delegate { writer.WriteRequiredUtf8("\ud800"); });
			}
		}

		[TestCase("taf:a", true, "five bytes is the minimum")]
		[TestCase("taf:", false, "prefix alone is not an identifier")]
		[TestCase("taf", false, "no prefix")]
		[TestCase("TAF:abc", false, "uppercase prefix")]
		[TestCase("taf:ABC", false, "uppercase body")]
		[TestCase("taf:a c", false, "whitespace")]
		[TestCase("taf:a\u00e9", false, "non-ASCII")]
		[TestCase("taf:a!b", false, "punctuation outside the allowed set")]
		[TestCase("taf:a.b_c:d-e", true, "every allowed punctuation")]
		[TestCase("taf:a\0b", false, "control character")]
		[TestCase("taf:a\ud800", false, "invalid surrogate")]
		[TestCase("", false, "empty")]
		[TestCase(null, false, "null")]
		public void IdentifierGrammarBoundaries(string value, bool expected, string why)
		{
			Assert.AreEqual(expected, KernelSemanticId.IsValid(value), why);
		}

		[Test]
		public void IdentifierLengthBoundariesAreExact()
		{
			Assert.IsTrue(KernelSemanticId.IsValid("taf:a"), "5 bytes accepted");
			Assert.IsFalse(KernelSemanticId.IsValid("taf:"), "4 bytes rejected");
			Assert.IsTrue(KernelSemanticId.IsValid("taf:" + new string('a', 124)), "128 bytes accepted");
			Assert.IsFalse(KernelSemanticId.IsValid("taf:" + new string('a', 125)), "129 bytes rejected");
		}

		[Test]
		public void EveryTupleFieldChangesTheEventId()
		{
			string baseline = IdFor(GoldenRules, GoldenSettlement, GoldenStream, GoldenKind, GoldenOrdinal);
			Assert.AreNotEqual(baseline, IdFor(4, GoldenSettlement, GoldenStream, GoldenKind, GoldenOrdinal), "rules version");
			Assert.AreNotEqual(baseline, IdFor(GoldenRules, "taf:settlement:other", GoldenStream, GoldenKind, GoldenOrdinal), "settlement");
			Assert.AreNotEqual(baseline, IdFor(GoldenRules, GoldenSettlement, "taf:stream:other", GoldenKind, GoldenOrdinal), "event stream");
			Assert.AreNotEqual(baseline, IdFor(GoldenRules, GoldenSettlement, GoldenStream, 2u, GoldenOrdinal), "kind");
			Assert.AreNotEqual(baseline, IdFor(GoldenRules, GoldenSettlement, GoldenStream, GoldenKind, 43uL), "ordinal");

			string seedChanged;
			KernelFaultCode fault;
			SemanticEventIdentity.TryCreateId(new KernelSeed128(1uL, 0x08090A0B0C0D0E0FuL), GoldenKey(), out seedChanged, out fault);
			Assert.AreNotEqual(baseline, seedChanged, "seed high");
		}

		[Test]
		public void TwoStreamsAtTheSameOrdinalAndKindProduceDistinctIdentities()
		{
			// The exact collision EventStreamId exists to prevent: two routes, same settlement,
			// same kind, both at ordinal zero.
			string a = IdFor(GoldenRules, GoldenSettlement, "taf:route:alpha", GoldenKind, 0uL);
			string b = IdFor(GoldenRules, GoldenSettlement, "taf:route:beta", GoldenKind, 0uL);
			Assert.AreNotEqual(a, b);
		}

		[Test]
		public void RecreatingTheSameTupleIsIdenticalAcrossTenThousandRepetitions()
		{
			string expected = GoldenEventDigestId;
			for (int i = 0; i < 10000; i++)
			{
				SemanticEventKey key;
				KernelFaultCode fault;
				SemanticEventKey.TryCreate(GoldenRules, GoldenSettlement, GoldenStream, GoldenKind, GoldenOrdinal, out key, out fault);
				string id;
				SemanticEventIdentity.TryCreateId(GoldenSeed(), key, out id, out fault);
				if (!string.Equals(expected, id, StringComparison.Ordinal))
				{
					Assert.Fail("identity drifted at repetition " + i);
				}
			}
		}

		/// <summary>
		/// Every enum value that can reach a wire or a fault report, pinned to its exact number.
		/// These are not arbitrary: a fault code is compared by callers, a job state and a latch
		/// value are encoded, and reordering any of these declarations would silently renumber
		/// them. A reader who adds a member in the middle should fail here rather than in a save.
		/// </summary>
		[Test]
		public void EveryWireEnumHoldsItsExactNumber()
		{
			// Fault codes. Callers branch on these and they appear in diagnostics.
			Assert.AreEqual(0, (int)KernelFaultCode.None);
			Assert.AreEqual(1, (int)KernelFaultCode.InvalidTick);
			Assert.AreEqual(2, (int)KernelFaultCode.InvalidInterval);
			Assert.AreEqual(3, (int)KernelFaultCode.ClockRegression);
			Assert.AreEqual(4, (int)KernelFaultCode.ArithmeticOverflow);
			Assert.AreEqual(5, (int)KernelFaultCode.InvalidOptionLatch);
			Assert.AreEqual(6, (int)KernelFaultCode.InvalidEventKey);
			Assert.AreEqual(7, (int)KernelFaultCode.InvalidToyState);
			Assert.AreEqual(8, (int)KernelFaultCode.CounterExhausted);
			Assert.AreEqual(9, (int)KernelFaultCode.InvalidRandomBound);
			Assert.AreEqual(10, (int)KernelFaultCode.CryptographicFailure);
			Assert.AreEqual(11, Enum.GetValues(typeof(KernelFaultCode)).Length, "a new fault code must be added at the end");

			// Job lifecycle. Declaration order is deliberately not lifecycle order — Blocked,
			// Cancelled, Recoverable and Compensated were appended after the happy path — so the
			// numbers are the contract and the reading order is not.
			Assert.AreEqual(0, (int)SemanticJobState.Scheduled);
			Assert.AreEqual(1, (int)SemanticJobState.Due);
			Assert.AreEqual(2, (int)SemanticJobState.Prepared);
			Assert.AreEqual(3, (int)SemanticJobState.Committed);
			Assert.AreEqual(4, (int)SemanticJobState.Materialized);
			Assert.AreEqual(5, (int)SemanticJobState.Notified);
			Assert.AreEqual(6, (int)SemanticJobState.Archived);
			Assert.AreEqual(7, (int)SemanticJobState.Blocked);
			Assert.AreEqual(8, (int)SemanticJobState.Cancelled);
			Assert.AreEqual(9, (int)SemanticJobState.Recoverable);
			Assert.AreEqual(10, (int)SemanticJobState.Compensated);
			Assert.AreEqual(11, Enum.GetValues(typeof(SemanticJobState)).Length);

			Assert.AreEqual(0, (int)JobTransitionVerdict.Rejected, "the default verdict must be refusal");
			Assert.AreEqual(1, (int)JobTransitionVerdict.Idempotent);
			Assert.AreEqual(2, (int)JobTransitionVerdict.Allowed);
			Assert.AreEqual(3, Enum.GetValues(typeof(JobTransitionVerdict)).Length);

			// Latch. Unobserved must be zero so a default-constructed latch is the unobserved one
			// rather than a settlement that silently believes the option is off.
			Assert.AreEqual(0, (int)OptionLatchValue.Unobserved, "default(OptionLatchValue) must be Unobserved");
			Assert.AreEqual(1, (int)OptionLatchValue.Disabled);
			Assert.AreEqual(2, (int)OptionLatchValue.Enabled);
			Assert.AreEqual(3, Enum.GetValues(typeof(OptionLatchValue)).Length);

			Assert.AreEqual(0, (int)OptionTransitionKind.None, "default must mean nothing happened");
			Assert.AreEqual(1, (int)OptionTransitionKind.InitializedDisabled);
			Assert.AreEqual(2, (int)OptionTransitionKind.InitializedEnabled);
			Assert.AreEqual(3, (int)OptionTransitionKind.Disabled);
			Assert.AreEqual(4, (int)OptionTransitionKind.Enabled);
			Assert.AreEqual(5, Enum.GetValues(typeof(OptionTransitionKind)).Length);

			// The underlying types are part of the wire too: widening any of these changes every
			// encoded length that contains one.
			Assert.AreEqual(typeof(byte), Enum.GetUnderlyingType(typeof(KernelFaultCode)));
			Assert.AreEqual(typeof(byte), Enum.GetUnderlyingType(typeof(SemanticJobState)));
			Assert.AreEqual(typeof(byte), Enum.GetUnderlyingType(typeof(JobTransitionVerdict)));
			Assert.AreEqual(typeof(byte), Enum.GetUnderlyingType(typeof(OptionLatchValue)));
			Assert.AreEqual(typeof(byte), Enum.GetUnderlyingType(typeof(OptionTransitionKind)));
		}

		/// <summary>
		/// Each half of the seed varied on its own. A writer that folded the two halves together —
		/// XOR, addition, or simply writing one twice — would still pass a test that only ever
		/// changes both at once, and would collide every pair of seeds with the same fold.
		/// </summary>
		[Test]
		public void BothSeedHalvesReachTheWireIndependently()
		{
			KernelSeed128 baseline = GoldenSeed();
			KernelFaultCode fault;
			byte[] bytes;

			Assert.IsTrue(KernelCanonicalEncoding.TryEncodeEventIdentityPreimage(baseline, GoldenKey(), out bytes, out fault));
			string baselineHex = Hex(bytes);

			// High only.
			Assert.IsTrue(KernelCanonicalEncoding.TryEncodeEventIdentityPreimage(
				new KernelSeed128(baseline.High ^ 1uL, baseline.Low), GoldenKey(), out bytes, out fault));
			string highChanged = Hex(bytes);
			Assert.AreNotEqual(baselineHex, highChanged, "the high half must reach the wire");

			// Low only.
			Assert.IsTrue(KernelCanonicalEncoding.TryEncodeEventIdentityPreimage(
				new KernelSeed128(baseline.High, baseline.Low ^ 1uL), GoldenKey(), out bytes, out fault));
			string lowChanged = Hex(bytes);
			Assert.AreNotEqual(baselineHex, lowChanged, "the low half must reach the wire");
			Assert.AreNotEqual(highChanged, lowChanged, "the halves must not be folded into one value");

			// The swap is the sharpest case: a symmetric fold gives these two the same bytes.
			Assert.IsTrue(KernelCanonicalEncoding.TryEncodeEventIdentityPreimage(
				new KernelSeed128(baseline.Low, baseline.High), GoldenKey(), out bytes, out fault));
			Assert.AreNotEqual(baselineHex, Hex(bytes), "swapping the halves must not produce the same preimage");

			// And the same four cases must separate the identities they produce, not merely the bytes.
			string a;
			string b;
			string c;
			string d;
			Assert.IsTrue(SemanticEventIdentity.TryCreateId(baseline, GoldenKey(), out a, out fault));
			Assert.IsTrue(SemanticEventIdentity.TryCreateId(new KernelSeed128(baseline.High ^ 1uL, baseline.Low), GoldenKey(), out b, out fault));
			Assert.IsTrue(SemanticEventIdentity.TryCreateId(new KernelSeed128(baseline.High, baseline.Low ^ 1uL), GoldenKey(), out c, out fault));
			Assert.IsTrue(SemanticEventIdentity.TryCreateId(new KernelSeed128(baseline.Low, baseline.High), GoldenKey(), out d, out fault));
			Assert.AreEqual(4, new HashSet<string> { a, b, c, d }.Count, "four distinct seeds, four distinct identities");
		}

		/// <summary>
		/// Byte, uint and ulong written at zero, one, and their maximum, in the exact widths the
		/// protocol fixes. A width that silently narrowed would still round-trip small values.
		/// </summary>
		[Test]
		public void EveryPrimitiveWidthIsExactAtItsBoundaries()
		{
			using (CanonicalByteWriter writer = new CanonicalByteWriter())
			{
				writer.WriteByte(0);
				writer.WriteByte(1);
				writer.WriteByte(255);
				Assert.AreEqual("0001ff", Hex(writer.ToArray()));
			}
			using (CanonicalByteWriter writer = new CanonicalByteWriter())
			{
				writer.WriteUInt32(0u);
				writer.WriteUInt32(1u);
				writer.WriteUInt32(uint.MaxValue);
				Assert.AreEqual("00000000" + "00000001" + "ffffffff", Hex(writer.ToArray()));
			}
			using (CanonicalByteWriter writer = new CanonicalByteWriter())
			{
				writer.WriteUInt64(0uL);
				writer.WriteUInt64(1uL);
				writer.WriteUInt64(ulong.MaxValue);
				Assert.AreEqual(
					"0000000000000000" + "0000000000000001" + "ffffffffffffffff",
					Hex(writer.ToArray()));
			}
			// The sign boundary, where a naive implementation flips into a negative and writes
			// something shorter or sign-extended.
			using (CanonicalByteWriter writer = new CanonicalByteWriter())
			{
				writer.WriteUInt32(2147483648u);
				writer.WriteUInt64(9223372036854775808uL);
				Assert.AreEqual("80000000" + "8000000000000000", Hex(writer.ToArray()));
			}
		}

		[Test]
		public void CultureDoesNotAlterBytesOrIds()
		{
			CultureInfo original = Thread.CurrentThread.CurrentCulture;
			try
			{
				byte[] bytes;
				KernelFaultCode fault;
				string id;
				foreach (string name in new string[] { "en-US", "tr-TR", "ar-SA", "de-DE" })
				{
					Thread.CurrentThread.CurrentCulture = new CultureInfo(name);
					KernelCanonicalEncoding.TryEncodeEventIdentityPreimage(GoldenSeed(), GoldenKey(), out bytes, out fault);
					Assert.AreEqual(GoldenEventPreimage, Hex(bytes), "bytes under " + name);
					SemanticEventIdentity.TryCreateId(GoldenSeed(), GoldenKey(), out id, out fault);
					// Turkish is the interesting one: a culture-sensitive formatter or casing call
					// produces a dotless i and silently breaks every identifier.
					Assert.AreEqual(GoldenEventDigestId, id, "id under " + name);
				}
			}
			finally
			{
				Thread.CurrentThread.CurrentCulture = original;
			}
		}

		[Test]
		public void EncodersRefuseADefaultKeyRatherThanEmittingNullIdentifiers()
		{
			byte[] bytes;
			KernelFaultCode fault;
			Assert.IsFalse(KernelCanonicalEncoding.TryEncodeEventIdentityPreimage(GoldenSeed(), default(SemanticEventKey), out bytes, out fault));
			Assert.AreEqual(KernelFaultCode.InvalidEventKey, fault);
			Assert.IsNull(bytes, "no partial value on failure");
		}

		[TestCase(0, "taf:settlement:test", "taf:stream:test", 1u)]
		[TestCase(3, null, "taf:stream:test", 1u)]
		[TestCase(3, "taf:settlement:test", null, 1u)]
		[TestCase(3, "taf:settlement:test", "taf:stream:test", 0u)]
		public void InvalidKeyComponentsAllReportInvalidEventKey(int rules, string settlement, string stream, uint kind)
		{
			SemanticEventKey key;
			KernelFaultCode fault;
			Assert.IsFalse(SemanticEventKey.TryCreate(rules, settlement, stream, kind, 0uL, out key, out fault));
			Assert.AreEqual(KernelFaultCode.InvalidEventKey, fault);
		}

		private static string IdFor(int rules, string settlement, string stream, uint kind, ulong ordinal)
		{
			SemanticEventKey key;
			KernelFaultCode fault;
			Assert.IsTrue(SemanticEventKey.TryCreate(rules, settlement, stream, kind, ordinal, out key, out fault));
			string id;
			Assert.IsTrue(SemanticEventIdentity.TryCreateId(GoldenSeed(), key, out id, out fault));
			return id;
		}
	}
}
#endif
